### ISSUE TITLE
报错No module named 'curl_cffi'

### ISSUE THREAD

**Issue by joyce677** [resphinas/claude-on-wechat-avaliable#7]
用的zeabur部署，这个依赖装不上

12:25:31[INFO][2023-09-01 04:25:30][bridge.py:38] - create bot claude for chat

12:25:31[ERROR][2023-09-01 04:25:30][chat_channel.py:278] - Worker return exception: No module named 'curl_cffi'

12:25:31Traceback (most recent call last):

12:25:31 File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run

12:25:31 result = self.fn(*self.args, **self.kwargs)

12:25:31 File "/app/channel/chat_channel.py", line 153, in _handle

12:25:31 reply = self._generate_reply(context)

12:25:31 File "/app/channel/chat_channel.py", line 175, in _generate_reply

12:25:31 reply = super().build_reply_content(context.content, context)

12:25:31 File "/app/channel/channel.py", line 37, in build_reply_content

12:25:31 return Bridge().fetch_reply_content(query, context)

12:25:31 File "/app/bridge/bridge.py", line 53, in fetch_reply_content

12:25:31 return self.get_bot("chat").reply(query, context)

12:25:31 File "/app/bridge/bridge.py", line 44, in get_bot

12:25:31 self.bots[typename] = create_bot(self.btype[typename])

12:25:31 File "/app/bot/bot_factory.py", line 44, in create_bot

12:25:31 from bot.claude.claude_ai_bot import ClaudeAIBot

12:25:31 File "/app/bot/claude/claude_ai_bot.py", line 5, in <module>

12:25:31 from curl_cffi import requests

12:25:31ModuleNotFoundError: No module named 'curl_cffi'

**Comment by resphinas** [comment]
https://blog.csdn.net/qq_37462361/article/details/132407922

**Comment by joyce677** [comment]
> https://blog.csdn.net/qq_37462361/article/details/132407922

zeabur跟railway一样是个容器平台，没办法使用终端命令吖

**Comment by joyce677** [comment]
> 不好意思 俺不太懂怎么弄docker....文档看了几篇也没整明白，能不能教教俺

docker我也不太懂啊，我用的是容器平台，那些容器平台是一键部署的，直接拉取的你github镜像，就不需要你像win或者linux 一样要自己去配置环境和依赖了，他自动会加载运行，你只需要等最后运行结果就行了。

我在win上测试了下，claude目前是私聊和群聊都共用一个上下文吗？不能分开？

**Comment by joyce677** [comment]
老哥啥时候把上传pdf,csv的功能加上去，要不完全发挥不了claude的优势。

**Comment by resphinas** [comment]
这种功能用电脑就好了，本身复杂的需要在电脑上完成的东西还用微信干嘛，直接登网页
